### ISSUE TITLE
Wall avoidance doesn't work reliably

### ISSUE THREAD

**Issue by SpitfireX** [Windfisch/agario-frickel#7] opened 2015-08-11 02:07 UTC
Most of the time the cell won't detect a wall and even gets locked up against it.
![screenshot 2015-08-11 04h05m16s](https://cloud.githubusercontent.com/assets/3309475/9188613/5f6bc394-3fde-11e5-8214-ec3b5d417f5e.png)
![screenshot 2015-08-11 04h12m24s](https://cloud.githubusercontent.com/assets/3309475/9188687/3fd65458-3fdf-11e5-9cbb-8fc5821acea1.png)
![screenshot 2015-08-11 04h14m29s](https://cloud.githubusercontent.com/assets/3309475/9188706/7a8a83d0-3fdf-11e5-8e3b-74838fd68966.png)
![screenshot 2015-08-11 04h16m37s](https://cloud.githubusercontent.com/assets/3309475/9188732/c61023f0-3fdf-11e5-9817-6c25b7bc1e35.png)

In this case the wall detection was kinda working but it kept constantly detecting and losing it again.
![screenshot 2015-08-11 04h37m43s](https://cloud.githubusercontent.com/assets/3309475/9188958/ba63980e-3fe2-11e5-9436-248a927e71e8.png)

**Comment by Windfisch** [comment] 2015-08-11 12:01
First and third image are not a bug. Wall avoidance is only done when running away; Chasing food close to the walls is fine.

Second and Fourth are fixed in commit 38bf13f

Fifth (constantly detecting and losing again) is an unrelated issue, the bot needs some knowledge about the past / "memory"

**Closed as completed by Windfisch** 2015-08-11 12:01 UTC
Labels: bug

**Comment by SpitfireX** [comment] 2015-08-11 12:43
> Fifth (constantly detecting and losing again) is an unrelated issue, the bot needs some knowledge about the past / "memory"

even if the other threats are deteced just fine but only the wall avoidance keeps "flickering" when right next to a wall (while running away from said other threats)?
